/**
 * KMS envelope encryption client — the ONLY authorized entry point for AWS KMS
 * operations in this codebase (CLAUDE.md §3.4.3).
 *
 * Direct imports of @aws-sdk/client-kms outside this module are forbidden.
 *
 * Implements INV-3 envelope scheme (§3.4.1):
 *   encrypt → KMS:GenerateDataKey → AES-256-GCM(plaintext, DEK) → zero DEK
 *   decrypt → KMS:Decrypt(encryptedDek) → AES-256-GCM decrypt → zero DEK
 *   fingerprint → KMS:GenerateMac(data, HMAC_KEY) for indexed lookups (§3.4.2)
 */

import {
  KMSClient,
  GenerateDataKeyCommand,
  DecryptCommand,
  GenerateMacCommand,
  MacAlgorithmSpec,
  type GenerateDataKeyCommandOutput,
  type DecryptCommandOutput,
  type GenerateMacCommandOutput,
} from '@aws-sdk/client-kms';
import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Environment — validated once at module load (§5.4 pattern applied to server)
// ---------------------------------------------------------------------------
const KmsEnvSchema = z.object({
  AWS_REGION:       z.string().min(1),
  KMS_CMK_ARN:      z.string().min(1),
  KMS_HMAC_KEY_ARN: z.string().min(1),
  // Application-level rotation version label written to kms_key_version column.
  // Increment this string when manually rotating and rewrapping stored DEKs.
  KMS_KEY_VERSION:  z.string().default('1'),
});

const kmsEnv = KmsEnvSchema.parse({
  AWS_REGION:       process.env['AWS_REGION'],
  KMS_CMK_ARN:      process.env['KMS_CMK_ARN'],
  KMS_HMAC_KEY_ARN: process.env['KMS_HMAC_KEY_ARN'],
  KMS_KEY_VERSION:  process.env['KMS_KEY_VERSION'],
});

const kmsClient = new KMSClient({ region: kmsEnv.AWS_REGION });

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const IV_BYTES       = 12 as const;   // AES-GCM standard IV length
const AUTH_TAG_BYTES = 16 as const;   // AES-GCM standard authentication tag length
const AES_ALGO       = 'aes-256-gcm' as const;
const DEK_KEY_SPEC   = 'AES_256' as const;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * Encrypted blob stored in enc_* table columns (§3.4.2).
 * All fields map directly to SQL columns of the same snake_case name.
 */
export type EncryptedPayload = {
  readonly ciphertext:    Buffer;
  readonly iv:            Buffer;  // 12 bytes
  readonly authTag:       Buffer;  // 16 bytes
  readonly encryptedDek:  Buffer;
  readonly kmsKeyId:      string;
  readonly kmsKeyVersion: string;
};

/** Subset of EncryptedPayload needed for decryption. */
export type DecryptInput = {
  readonly ciphertext:   Buffer;
  readonly iv:           Buffer;
  readonly authTag:      Buffer;
  readonly encryptedDek: Buffer;
  readonly kmsKeyId:     string;
};

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Overwrites a Buffer's memory with zeros to minimize window during which a
 * plaintext DEK resides in process memory (§3.4.1).
 * Note: JS GC does not guarantee memory erasure; explicit zeroing is best-effort
 * mitigation. Pair with short-lived function scopes to limit DEK lifetime.
 */
function zeroBuffer(buf: Buffer): void {
  buf.fill(0);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Encrypts `plaintext` under a fresh per-record DEK generated by KMS.
 * The plaintext DEK is zeroed immediately after the cipher operation (§3.4.1).
 *
 * @returns EncryptedPayload ready for direct column insertion in enc_* tables.
 */
export async function encryptPayload(plaintext: Buffer): Promise<EncryptedPayload> {
  const keyResp: GenerateDataKeyCommandOutput = await kmsClient.send(
    new GenerateDataKeyCommand({
      KeyId:   kmsEnv.KMS_CMK_ARN,
      KeySpec: DEK_KEY_SPEC,
    }),
  );

  if (!keyResp.Plaintext || !keyResp.CiphertextBlob || !keyResp.KeyId) {
    throw new Error('KMS GenerateDataKey returned an incomplete response');
  }

  const dek         = Buffer.from(keyResp.Plaintext);
  const encryptedDek = Buffer.from(keyResp.CiphertextBlob);
  const iv           = randomBytes(IV_BYTES);

  let ciphertext: Buffer;
  let authTag:    Buffer;

  try {
    // createCipheriv narrows to CipherGCM when algorithm is a CipherGCMTypes literal,
    // making getAuthTag() available without a cast.
    const cipher = createCipheriv(AES_ALGO, dek, iv);
    ciphertext   = Buffer.concat([cipher.update(plaintext), cipher.final()]);
    authTag      = cipher.getAuthTag(); // 16 bytes by default for GCM
  } finally {
    zeroBuffer(dek);
  }

  return {
    ciphertext,
    iv,
    authTag,
    encryptedDek,
    kmsKeyId:      keyResp.KeyId,
    kmsKeyVersion: kmsEnv.KMS_KEY_VERSION,
  };
}

/**
 * Recovers plaintext from an EncryptedPayload by decrypting the DEK via KMS,
 * then applying AES-256-GCM decryption. The plaintext DEK is zeroed immediately
 * after use (§3.4.1). Throws if authentication fails or KMS rejects the request.
 */
export async function decryptPayload(input: DecryptInput): Promise<Buffer> {
  const decryptResp: DecryptCommandOutput = await kmsClient.send(
    new DecryptCommand({
      KeyId:          input.kmsKeyId,
      CiphertextBlob: input.encryptedDek,
    }),
  );

  if (!decryptResp.Plaintext) {
    throw new Error('KMS Decrypt returned empty plaintext');
  }

  const dek = Buffer.from(decryptResp.Plaintext);

  try {
    const decipher = createDecipheriv(AES_ALGO, dek, input.iv);
    decipher.setAuthTag(input.authTag);
    return Buffer.concat([decipher.update(input.ciphertext), decipher.final()]);
  } finally {
    zeroBuffer(dek);
  }
}

/**
 * Generates a deterministic HMAC-SHA256 fingerprint for a value using a
 * dedicated KMS HMAC key. Intended for `*_fp bytea` columns that allow indexed
 * lookups on encrypted tables without exposing plaintext (§3.4.2).
 *
 * IMPORTANT: The HMAC key (KMS_HMAC_KEY_ARN) MUST be distinct from the
 * encryption CMK (KMS_CMK_ARN). Never use the same key for both purposes.
 */
export async function generateHmacFingerprint(data: Buffer): Promise<Buffer> {
  const macResp: GenerateMacCommandOutput = await kmsClient.send(
    new GenerateMacCommand({
      KeyId:        kmsEnv.KMS_HMAC_KEY_ARN,
      Message:      data,
      MacAlgorithm: MacAlgorithmSpec.HMAC_SHA_256,
    }),
  );

  if (!macResp.Mac) {
    throw new Error('KMS GenerateMac returned empty MAC');
  }

  return Buffer.from(macResp.Mac);
}
